### PR TITLE
Don't wait until after the move to activate Protean

### PR DESCRIPTION
**Pull request by urkerab**
I don't know whether this is the best place to add this or the best way of implementing it but it seems to work.

### CODE REVIEW

**Comment by Zarel** [comment]
This seems like the wrong place to do it...

**Comment by urkerab** [comment]
So, it seems to work here too, if that's what you were thinking of?

**Comment by Zarel** [comment]
Can you more clearly describe what the problem is and how this commit fixes it?

**Comment by urkerab** [comment]
Before:
Pokemon used **Move**!
(move animates)
<small>[Pokemon's Protean]
Pokemon transformed into the Type type!</small>
After:
Pokemon used **Move**!
<small>[Pokemon's Protean]
Pokemon transformed into the Type type!</small>
(move animates)

**Comment by urkerab** [comment]
Alternative approach: change some of the Protean code:

    this.attrLastMove('[still]');
    this.add('-start', source, 'typechange', type);
    if (!move.flags['charge'] || pokemon.volatiles[move.id]) this.add('-anim', source, move, target);

**Comment by Zarel** [comment]
Give me some time to think about this.

**Comment by urkerab** [comment]
Storm Drain and Lightning Rod's handlers activate before Protean's does, and I think Protean fails if the move has no target, so you can't change that, so Protean may not actually be the next step, and the suggested server-side change is definitely wrong.

**Comment by Zarel** [comment]
This has been long-fixed, and as of 8dc8037fd8c I consider the Protean animation basically perfect.

**Comment by Zarel** [comment]
https://replay.pokemonshowdown.com/oumonotype-82345404

is a good replay file to refer to, if you want to see what Protean currently looks like.

**Comment by urkerab** [comment]
That's... an ancient replay. Try something newer, such as https://replay.pokemonshowdown.com/gen7pu-666651723 and you'll see the move animating before Protean's typechange.

**Comment by Zarel** [comment]
It should probably be fixed to work more like the old replay, then. :[

**Comment by Zarel** [comment]
It's insane to change the client to work around a server bug.

**Comment by urkerab** [comment]
Server bug? Do you want Protean's message to be inserted before the last move? I guess that's doable...

**Comment by Zarel** [comment]
Yes.

**Comment by Zarel** [comment]
Well, actually, it depends basically purely on, how does it work in-game?

```
Pokemon used Move!
[Pokemon's Protean]
Pokemon transformed into the Type type!
(move animates)
```

or

```
[Pokemon's Protean]
Pokemon transformed into the Type type!
Pokemon used Move!
(move animates)
```

**Pull request closed without merging**
