### PR TITLE
Teambuilder: Create a button which allows users to clone/duplicate their team.

### PR DESCRIPTION
**Pull request by HappyZombies**
Hello, I am requesting a pull request that contains functionality that will allow users to clone their teams.

Currently, if a user wants to have a copy of an existing team (say they want the same team but maybe with different moves, different items, different pokemons, etc.) they must first: Go to the export/import menu, copy the text, go back and create a new team, go back into export/import, paste the team and save. 

The clone button allows a user to instantly clone a team. After a team is cloned, the name of the team will have " Clone of" appended to the beginning of it. See the screenshots below to see how the clone button works. 

clone-button

clone-of-title

_After duplicating the two teams and going back..._
after-cloning

A margin 10px was added to the ".teamlist li" on the CSS. When adding another button next to the edit and delete button, it causes it to go to the next line (which ends up underneath each teamlist). So I pushed all of the tools underneath of the team list display. I am not sure if this looks nice or if it is something you would like, but a review of the positioning of the clone button might need to be discussed. 

Anyhow, thank you for your time and I hope that this feature is implemented soon as it will help a lot of people!

### CODE REVIEW

**Comment by Slayer95** [comment]
Can we do this with Ctrl+DnD? The team controls are supposed to be to the right of the main team button...

**Comment by HappyZombies** [comment]
@Slayer95 Okay, how about Ctrl+DnD on the 'New Team' button and it clones the team ?

**Comment by Zarel** [comment]
There should probably also be a button, though...

**Comment by Zarel** [comment]
Superseded by #1058, which still doesn't look how I'd prefer...

**Pull request closed without merging**
