### PR TITLE
Don't use toId for room names while joining a room using popup

### PR DESCRIPTION
**Pull request by xfix**
This fixes the issue that the Join room popup couldn't be used to enter battle rooms.

### CODE REVIEW

**Comment by Slayer95** [comment]
It should use ``toRoomid`` instead, which correctly handles battle rooms.

**Comment by Zarel** [comment]
What @Slayer95 said.

**Comment by xfix** [comment]
Fixed.

**Comment by xfix** [comment]
@Zarel Sorry, I was quite busy lately. My fault.

**Pull request merged**
