### PR TITLE
Update Infobox CSS

### PR DESCRIPTION
**Pull request by Lord-Haji**
Infobox comes with curved edge looks nice :D

### CODE REVIEW

**Comment by Zarel** [comment]
......I guess it can be a vote. `25px` is probably _too_ rounded even if rounded looks nice, though...

**Comment by bumbadadabum** [comment]
Can you attach a screenshot comparison?

**Comment by Lord-Haji** [comment]
scrnst
Here's the screen shot
But i do think if rounded edges we should make the border 3px or 4px

**Comment by bumbadadabum** [comment]
If you're doing this you might need to add some padding too.

**Comment by Lord-Haji** [comment]
@bumbadadabum is the border radius and border width perfect ?

**Comment by bumbadadabum** [comment]
Too rounded imo. Also I'm not a fan of this in general but this isn't up to
me.

**Comment by Lord-Haji** [comment]
Update:
newscrnsht
Now it looks like this

**Comment by kotarou3** [comment]
What about multiple lines?

Also, still feels too round to me

**Comment by Ridaz** [comment]
It occupies too much space just for info and like bumba said, it's too round and doesn't blend in with the rest of the PS layout

**Comment by Lord-Haji** [comment]
Updated the Infobox CSS.
Reduced the roundness almost like the PS Battle Buttons.
Also added  the roundness to the:- 
* broadcast-red
* broadcast-blue
* broadcast-green

**Comment by Lord-Haji** [comment]
@Zarel 
broadcast
Final screen shots of broadcast. But i do think we also should think of using some other good looking color hex. NP if its a down vote tho

**Comment by Lord-Haji** [comment]
infobox
Final screen shot of infobox @Zarel

**Comment by Zarel** [comment]
I think those have way too much padding for how often we currently use them.

**Comment by Lord-Haji** [comment]
@Zarel  shall i go back to the ``2px 4px padding`` then ?

**Comment by Zarel** [comment]
Probably. At most one more pixel.

**Comment by panpawn** [comment]
I am not a fan of these changes.

**Comment by panpawn** [comment]
Also, "Infobox"... "box"...

A "box" is defined as: "a container with a flat base and sides, **typically square or rectangular** and having a lid." ([Source](https://www.google.com/search?q=define+box&ie=utf-8&oe=utf-8))

With that being said, the name of this CSS class seems unfit to me if we deviate from this.  But that's just my opinion.  That, and well, I don't think it looks as professional as a true "box".

**Comment by Zarel** [comment]
No updates in three-ish months and most people don't like this in its current state; closing.

**Pull request closed without merging**
