### PR TITLE
Use Wikimedia's css sanitizer for custom css parsing

### PR DESCRIPTION
**Pull request by supersoniko**
As discussed in pms @Zarel 

 - Full css3 support (old sanitizer didn't have this)
 -  Covers all xss attacked listed at https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet

Main purpose: Allow side servers to have css3 in their custom css

*Nii Sama*

### CODE REVIEW

**Comment by panpawn** [comment]
There HAS to be an easier way to do this.

This is much too much.

**Comment by supersoniko** [comment]
If you can show me sure, I've done my research and this is the only library that fulfills these requirements.
I don't think its more than htmlpurifier and csstidy library anyway?

**Comment by panpawn** [comment]
See https://github.com/Zarel/Pokemon-Showdown-Client/issues/248

**Comment by supersoniko** [comment]
Anyway it's csstidy that's the problem not htmlpurifier, Zarel said he was good with this library.

**Comment by panpawn** [comment]
I don't see why we should add an entire new library where we don't necessarily have to is all

**Comment by supersoniko** [comment]
More like replacing, since we can remove htmlpurifier and csstidy. I'll look into kota's solution if @Zarel wants that.

**Comment by Zarel** [comment]
If someone _wants_ to port to Caja, that's fine by me, but barring that, I consider MediaWiki sufficiently trustworthy to publish a CSS sanitizer.

**Comment by Zarel** [comment]
(Also, the MediaWiki sanitizer is easier for us to use because it's written in PHP, unlike Caja.)

**Comment by Zarel** [comment]
Also, is our old sanitizer not in Git?

**Comment by Zarel** [comment]
Oh, it's in the other repository. Yeah, this is better.

**Comment by supersoniko** [comment]
We could use a package manager like Composer to easily maintain libraries. I don't know if we use enough php libraries to warrant such a change though. Anyhow that's a different issue than what I'm trying to solve in this PR.

**Comment by Zarel** [comment]
And yes, I validated the CSS sanitizer code, it's unmodified from the official `css-sanitizer-1.0` from Wikimedia.

**Pull request merged**
