### PR TITLE
Add CAP NFE

### PR DESCRIPTION
**Pull request by DeathlyPlays**
In tandem with https://github.com/Zarel/Pokemon-Showdown/pull/3821

### CODE REVIEW

**Comment by xfix** [comment]
Test failure seems unrelated to this commit, test works on my computer. The location where it failed (while trying to retrieve list of formats) suggests it failed as it wasn't able to connect to Pokemon Showdown server (that is started during tests).

**Comment by DeathlyPlays** [comment]
@xfix precisely my thoughts, hence why I reached out trying to contact you on main

**Comment by Zarel** [comment]
You can just restart the build.

**Comment by DeathlyPlays** [comment]
@Zarel wouldn't let me

**Comment by Zarel** [comment]
I was talking to xfix, I know you can't

**Comment by xfix** [comment]
@Zarel I cannot either (I only have commit rights to server, not client)

**Comment by Zarel** [comment]
Oh, yeah, that should be fixed

**Pull request merged**
