### PR TITLE
Mouseovers for users/battle on joinroom page

### PR DESCRIPTION
**Pull request by panpawn**
For the users button, this adds the mouse-over message "Find an online user" and for the battle button, "Find an active battle".

### CODE REVIEW

**Comment by Slayer95** [comment]
Remove "click to"

**Comment by panpawn** [comment]
Removed

**Comment by Zarel** [comment]
Can we not have `.`? "Find an active battle" is a sentence fragment in context.

Also, "Find an online user" reads better (and parallels "active battle" better).

**Comment by panpawn** [comment]
Done

**Pull request merged**
