### PR TITLE
Dark Mode: Improve credits readability

### PR DESCRIPTION
**Pull request by TheFenderStory**

### CODE REVIEW

**Comment by panpawn** [comment]
Screen cap of before/after?

**Comment by Zarel** [comment]
Seems unnecessary when Credits is only an easter-egg on the teambuilder...

**Comment by TheFenderStory** [comment]
I mean your call. I made the pr after clicking into it by chance and not being able to read it which seemed weird. 
image Here's a screen cap if you'd like one

**Comment by Zarel** [comment]
Might be better if we just replaced the Credits button in the teambuilder.

**Comment by TheFenderStory** [comment]
If you let me know what you want done i can take care of that for you. Otherwise feel free to close the pull request.

**Comment by Zarel** [comment]
I mean, the dialog section of the teambuilder is in my voice, so it's really not like anyone else can edit it.

**Comment by Zarel** [comment]
I fixed this by removing the Credits entirely in be0ca58192ef

**Pull request closed without merging**
