### PR TITLE
Darkmode: Change roomtab color scheme from default

### PR DESCRIPTION
**Pull request by panpawn**
Screencap:

### CODE REVIEW

**Comment by panpawn** [comment]
Updated Screencap:

**Comment by Zarel** [comment]
I don't think that necessarily looks better. The active tab should be at least the same color as the bar below it.

I'm also not sure I like that color scheme. Looks a bit too "Halloween"...

**Comment by panpawn** [comment]
>The active tab should be at least the same color as the bar below it.

It is. (see second screen cap; "Studio" is the active room)

**Comment by panpawn** [comment]
>I'm also not sure I like that color scheme.

Is it specifically with the orange?  Would you prefer me to look into a different color combination; perhaps blue and black?

**Comment by Zarel** [comment]
There's a gap between the tab and the bar under it, which shouldn't be there. Compare the current:

image

I think a more yellowish orange would make it look less Halloweeny. Also consider toning down saturation/brightness.

**Comment by WallyTheBully** [comment]
Updating this part of the darkmode CSS may be a good idea, however a linear-gradient might be better with other colors

**Comment by panpawn** [comment]
I will be looking into updating this shortly.  Thank you for your feedback thus far!

**Comment by panpawn** [comment]
>however a linear-gradient might be better with other colors 

I'm not sure I agree about that for this part of the CSS, trying to remain as close to the opposite of what not-darkmode looks like as possible for this, specifically... as in, color wise, if that makes sense?  What do other people think about this?

Here is my updated screen cap:


Does that look better?

Specifically, I addressed the gap you were talking about that shouldn't of been there, and I also revised the color to be more of "yellowish orange".

Feedback much appreciated!

**Comment by panpawn** [comment]
It was pointed out to me that the highlighted room border looked off, so I went ahead and fixed that:

**Comment by Zarel** [comment]
It needs to be a _lot_ more yellowish.

You still have that weird black line between the tab and the separator.

**Comment by panpawn** [comment]
>You still have that weird black line between the tab and the separator.

I was toggling between this darkmode and lightmode, and lightmode has a faint gray bar between the separator, much like this faint black bar.  I'm confused :|

**Comment by panpawn** [comment]
@Zarel - it looks different on different browsers.  On Firefox (which is what I'm using), lightmode room tabs look like this:

Are you on Chrome?

**Comment by panpawn** [comment]
Updated screen cap:

**Comment by panpawn** [comment]
Alternate idea, since this this "more yellow" is getting cringe-worthy:

This uses the blue from the PS logo, so that it looks more complimentary to the rest of PS (kind of).

Thoughts?  Should I go back on the [yellow brick road](https://s-media-cache-ak0.pinimg.com/originals/ea/b0/7f/eab07f7969e91626f0acd8f8f295f8af.jpg)?

(PS - this is updated to use the previous posts yellow - **NOT** this blue!)

**Comment by Zarel** [comment]
Blue works, although cool colors aren't great for a dark theme, but I guess it's worth a try.

First, though, that blue needs to be lightened and desaturated. Right now you don't have enough contrast.

**Comment by panpawn** [comment]
Updated with:

**Comment by Zarel** [comment]
Should definitely be desaturated. And you still haven't fixed the border issue.

**Comment by panpawn** [comment]
>And you still haven't fixed the border issue.

... I'm not sure I understand what you mean by that :|

**Comment by Zarel** [comment]
> @Zarel - it looks different on different browsers

This actually has nothing to do with different browsers, this is all about zoom level. Set zoom level to 100% or 200% on either Chrome or Firefox, and it'll look like my screenshot.

**Comment by panpawn** [comment]
ohh, okay, I just tried to see what it looks like in 100% zoom level for me, here's what it looks like:

**Comment by panpawn** [comment]
Updated screen cap:

**Comment by Zarel** [comment]
Still need you to desaturate it...

**Comment by panpawn** [comment]
Updated screen cap:

**Comment by panpawn** [comment]
Is that better?

**Comment by Zarel** [comment]
It's better, but maybe a bit darker?

**Comment by panpawn** [comment]
Updated with:

**Comment by panpawn** [comment]
Is that good?

**Comment by Zarel** [comment]
Better. Possibly good enough.

**Comment by panpawn** [comment]
Is it... good enough?

**Comment by Zarel** [comment]
*exaggerated sigh*

I guess it's better than what we currently have...

**Comment by Zarel** [comment]
And the reason I left it on hold for so long is that there's a lot of minor things wrong with it.

I fixed these: 0529b95ffe560b0

1. active tabs without close buttons weren't being styled correctly (they were displaying like inactive tabs)
2. active tabs without close buttons were having their styles overridden on hover
3. the bottom bar color was weird

Still broken:

1. no active states: background color should be different when mouse is down

and some other stuff

**Comment by panpawn** [comment]
Also, now broken is hovering over tabs that you've been highlighted in.

**Pull request merged**
