### PR TITLE
Tournaments: highlight users in the bracket

### PR DESCRIPTION
**Pull request by sirDonovan**
Screenshot: http://i.imgur.com/7KWoNwh.png

### CODE REVIEW

**Comment by Zarel** [comment]
Hm. We could use username colors for this.

**Comment by sirDonovan** [comment]
It's not as effective for users with darker colors: http://i.imgur.com/nwlqM2F.png. If you meant using their colors instead of the blue, that wouldn't help users who have colors similar to the existing red/green.

**Comment by Zarel** [comment]
We could lighten the existing red/green until they look good.

**Comment by sirDonovan** [comment]
I tried multiple opacity levels, from the current down to 1%. Highlighted usernames don't stand out enough to be easily seen while scrolling through the bracket, compared to highlighted nodes: http://i.imgur.com/VgGwm3e.png http://i.imgur.com/lW8ccmf.png http://i.imgur.com/K9V6Nq1.png

**Comment by TheImmortal** [comment]
@Zarel is there a need to use username colors? I like the blue, personally.

**Comment by kotarou3** [comment]
Agreeing with @TheImmortal

**Comment by Zarel** [comment]
I don't see the need for any highlighting at all, in that case...

**Comment by TheImmortal** [comment]
@sirDonovan didn't mention why this change but I assume because it's useful for huge tournaments.

**Comment by Zarel** [comment]
Well, at least pick nicer colors. The example screenshot was really ugly, which might be part of why it seems useless to me.

**Comment by Slayer95** [comment]
What about adding some way to center the tournament bracket on the current user battle? Maybe listen to the Spacebar key pressing?

**Comment by Zarel** [comment]
PS has text boxes that should be usually-focused, which makes Spacebar a bit of a suboptimal choice for keyboard shortcut.

**Comment by kotarou3** [comment]
@Slayer95 
I was originally thinking of adding a button of sorts to centre the user, but I never got around to that.

**Comment by sirDonovan** [comment]
How's this color? http://i.imgur.com/vo71KBH.png

**Comment by sirDonovan** [comment]
Superseded by https://github.com/Zarel/Pokemon-Showdown-Client/pull/515.

**Pull request closed without merging**
