### PR TITLE
Remove and appropriately replace curTeamIndex

### PR DESCRIPTION
**Pull request by augmt**
Addresses [this issue comment](https://github.com/Zarel/Pokemon-Showdown-Client/pull/541#issuecomment-154016280).

### CODE REVIEW

**Comment by Zarel** [comment]
I'm like 80% sure this was superseded by a different pullreq. Reopen if I'm wrong.

**Comment by augmt** [comment]
Can't seem to find said pull request.

**Comment by Zarel** [comment]
lol, I think this may have been the pull request I was thinking of

**Comment by Zarel** [comment]
No, it's not.

**Comment by Zarel** [comment]
In any case, the current version of PS already properly updates `curTeamIndex`, so whether or not you can find such a pull request or commit, it seems clear that this pullreq has been superseded.

**Pull request closed without merging**
