### PR TITLE
Tournaments: support showing users who have joined

### PR DESCRIPTION
**Pull request by sirDonovan**
During signups in elimination tournaments, show the number of users who
have joined in place of the empty bracket

Screenshot: http://i.imgur.com/dg2xE1s.png

### CODE REVIEW

**Comment by TheImmortal** [comment]
Why not show the users as well? Like by clicking that.

**Comment by Zarel** [comment]
Can you just show a list of rooms?

**Comment by Zarel** [comment]
Can you just show a list of all the users? Yeah, what TI said.

**Comment by sirDonovan** [comment]
Can we do both? http://i.imgur.com/HK2HKTw.png

Some people may only need the number while others may want to see individual users.

**Pull request merged**
