### PR TITLE
Add some activation messages for the new Abilities

### PR DESCRIPTION
**Pull request by urkerab**
- Battle Bond
- Disguise
- Power Construct

I copied the use of `-formechange` from Shaymin-Sky's transformation.

### CODE REVIEW

**Comment by Marty-D** [comment]
You'd have to send `-formechange` from the server for all of these then, and their Abilities would be activating twice, which would be slow and ugly. I was actually thinking about combining `-mega`, `-primal`, and these new ones under a `-permaformechange` or something. And since these new ones have two messages each, the Ability activation can be handled by the `-activate` part, which you've already done here. The Shaymin thing was mostly a hack so I could make use of the existing "POKEMON transformed!" default message. :sweat_smile:

**Comment by Zarel** [comment]
`-permaformechange` already exists, it's called `detailschange`...

**Comment by Marty-D** [comment]
@Zarel, what makes `-mega` and `-primal` special then?

**Comment by Zarel** [comment]
No idea, I didn't add them.

**Comment by Zarel** [comment]
Please tell me `detailschange` is still sent for megaing...

**Comment by Zarel** [comment]
Oh, good, it is. A permanent change to a Pokémon's species is a major.

Anyway, as far as I can tell, someone just decided to send separate messages for the mega and primal messages? I'd personally have used `[mega]` and `[primal]` tags on `detailschange`.

**Comment by Marty-D** [comment]
Unfortunately those already exist so we have to keep supporting them... But yeah, those tags are what I was thinking so doing it on `detailschange` instead is fine with me.

**Comment by urkerab** [comment]
We can't do mega/primal on detailschange because of BH Illusion shenanigans, unfortunately.

**Comment by Zarel** [comment]
Can you clarify?

**Comment by ascriptmaster** [comment]
IIRC Illusion is coded in such a way where if you mega evolve while under Illusion, you keep the illusion appearance (until you switch out? forever? idr but it won't break under damage any more because the ability is no longer Illusion)

I don't know if this is the same scenario that's being brought up, though.

**Comment by Marty-D** [comment]
Yeah what ascriptmaster said (until you switch). I forgot it also uses `-mega` and `-primal` for the Illusion message/animation/cry that happens in those situations.

**Comment by urkerab** [comment]
(I wasn't proposing to send the Ability with the `-formechange` minor, but as we're going with `detailschange` anyway, it doesn't matter.)

**Comment by Zarel** [comment]
...I'm going to leave this to Marty to decide...

**Comment by Marty-D** [comment]
This is fine; all future permanent forme changes can follow this model. Thanks @urkerab! :+1:
I'll handle the removal of placeholders server-side.

**Pull request merged**
