### PR TITLE
Tooltips: Fix Twisted Spoon

### PR DESCRIPTION
**Pull request by MacChaeger**
It has a space in newer generations.

### CODE REVIEW

**Comment by Zarel** [comment]
You forgot to remove the old entry...

**Comment by MacChaeger** [comment]
I left it in because it didn't have a space in the name until Gen 6, but it
seems like older generation mods don't change it back to one word. Should
they?

**Comment by Zarel** [comment]
They intentionally don't. Also you left it in but also didn't add a `,` which is why the build is failing, if you didn't notice.

**Comment by Zarel** [comment]
Either way, I'd recommend taking out the old line entirely.

**Comment by urkerab** [comment]
> Also you left it in but also didn't add a , which is why the build is failing

We don't enforce trailing `,` on the client like we do on the server?

**Comment by Zarel** [comment]
We can't, Safari 5 (?) and IE7 don't support them.

...I guess in theory we can drop support for those by now. The last time we got a bug report about breaking Safari 5 compatibility was like 4 years ago.

**Comment by Zarel** [comment]
Safari 5 is I think relevant for being the most recent version of Safari supported on the iPad 1.

**Comment by Zarel** [comment]
I wouldn't be surprised if the Wii/3DS browser didn't support them either, though.

**Comment by AustinXII** [comment]
The 3DS doesn't even support JS

**Comment by Zarel** [comment]
Weird, I thought I heard someone talking about playing PS on the 3DS browser.

Anyway, I just researched and can confirm that Safari 5 doesn't support trailing commas, and that Safari 5 is the most recent version of Safari supported on the original iPad.

**Comment by AustinXII** [comment]
I've actually tried, but sadly it's impossible on the 3DS :(

**Comment by urkerab** [comment]
> We can't, Safari 5 and IE7 don't support them.

The code that sets the following variables currently uses trailing commas: `BattleTooltips.zMoveTable`, `BattleTooltips.orbUsers`, `BattleTooltips.orbTypes`, `Config.groups`. Do you want those places fixed?

> ...I guess in theory we can drop support for those by now. The last time we got a bug report about breaking Safari 5 compatibility was like 4 years ago.

... or not?

**Comment by Zarel** [comment]
> The code that sets the following variables currently uses trailing commas:

...I thought our linter checked for that...

**Comment by Zarel** [comment]
...why is Travis not catching this?

**Pull request merged**
