### PR TITLE
sparse 3 second delay after clicking "Battle!"

### PR DESCRIPTION
**Pull request by acz13**
A little too simple perhaps?

### CODE REVIEW

**Comment by Zarel** [comment]
Indentation needs to be fixed, but otherwise I think this looks pretty good.

Maybe rename `delay` to `searchDelay`.

**Comment by acz13** [comment]
erm something went wrong???

**Comment by bumbadadabum** [comment]
You didn't need to close this.

**Comment by acz13** [comment]
Ok while i was squashing commits something must have happened ???
The commit disappeared...

**Comment by bumbadadabum** [comment]
Just try it again?

**Comment by bumbadadabum** [comment]
I mean, if you still have it locally.

**Comment by panpawn** [comment]
Reminder to never force push when to a PR's branch if that PR is closed....

**Pull request closed without merging**
