### PR TITLE
Adding tiled custom background option

### PR DESCRIPTION
**Pull request by mashirochan**
Added a drop down box during custom background selection to have the option to make it tile, rather than stretch the image across the whole screen. Would be a useful feature to have if some users find the need, but not necessary if they don't want it.

screenshot 2015-05-11 at 11 02 13 pm

### CODE REVIEW

**Comment by SolarisFox** [comment]
@xfix thoughts?

**Comment by Zarel** [comment]
This isn't great UI... now that the window has more than one option, there should probably be an "OK" button instead of automatic-take-effect-when-file-is-selected.

But I'm not sure how useful this is. Do you personally want to use this feature?

**Comment by mashirochan** [comment]
There are a lot of cool tiled backgrounds out there that I would probably use myself, given the chance. And I could move the drop-down menu and the file input on the same line and then add a Submit button underneath next the the Cancel button (still working on getting both inputs on the same line).

screenshot 2015-05-12 at 3 32 46 pm

**Comment by Zarel** [comment]
That looks better, yes.

**Comment by Zarel** [comment]
We've overhauled the background menu. If you feel tiled backgrounds are important enough to implement in the new menu, feel free to pullreq an updated version.

**Pull request closed without merging**
