### PR TITLE
Teambuilder Hack for Dual Wielding

### PR DESCRIPTION
**Pull request by Spandamn**
Do not merge; The code for Dual Wielding is not ready yet
[OMotM October](http://www.smogon.com/forums/threads/om-of-the-month-october-winner-dual-wielding.3616125/#post-7527701)

### CODE REVIEW

**Comment by Zarel** [comment]
...why not? This doesn't hurt to merge early, does it?

**Comment by Spandamn** [comment]
it doesn't but the only thing holding it back is the fact the the code for dual wielding is incomplete.
If it isn't completed, then another OMotM would have to be chosen, removing the need for this PR

**Comment by Spandamn** [comment]
Actually merge it @Zarel, it'd be easy for teambuilders while testing

**Comment by Zarel** [comment]
Code style is wrong, we require braces for multiline if/else blocks.

**Pull request merged**
