### PR TITLE
Sacred & Secret Sword Animation Update

### PR DESCRIPTION
**Pull request by Ridaz**
No longer a "sword that claws"
sacred sword

### CODE REVIEW

**Comment by Zarel** [comment]
Why not a single slash? We have a slash particle...

**Comment by ascriptmaster** [comment]
We don't actually have a slash particle at this moment. I don't know which animation you're looking at but it's probably achieved with fast moving white particles.

**Comment by Zarel** [comment]
I was actually talking about the claw particle, which you would have known if you'd checked in the Dev room at all. <_<

**Comment by Zarel** [comment]
Which in hindsight I kind of understand why you're not using it, but seriously, I don't like this look. A bunch of balls doesn't say "slash" to me.

**Comment by Ridaz** [comment]
Sacred Sword:
sacred sword

Secret Sword:
secret sword

**Comment by ascriptmaster** [comment]
My understanding from the pull request initial comment was that we were specifically taking out the claw graphic, hence my assumption that we weren't going to use that as our "slash" particle

**Pull request merged**
