### PR TITLE
Support parsing versions and config from servers

### PR DESCRIPTION
**Pull request by Slayer95**
Version support client-side and login-server-side.
Config support stubbed only client-side. Possible usage for it includes custom ranks / rank sorting (# vs ~ comes to mind)

(Be harsh in PHP review)

### CODE REVIEW

**Comment by Zarel** [comment]
Is there a need for this so far?

**Comment by Slayer95** [comment]
Not really, but can we get this covered before thinking of removing the "Beta" label?

**Comment by Zarel** [comment]
I don't think we'll ever have a breaking change that requires something like this.

If we did, I'd honestly prefer to post-process old replays than support multiple protocol versions.

**Comment by Slayer95** [comment]
I think that's overly optimistic in the light of all these issues with pending protocol updates:

https://github.com/Zarel/Pokemon-Showdown-Client/issues/314
https://github.com/Zarel/Pokemon-Showdown/pull/1269
https://github.com/Zarel/Pokemon-Showdown/issues/1452

Replay postprocessing sounds like a good idea, but it would still need to accurately determine the version of the protocol, and checking dates is not enough.

**Comment by Zarel** [comment]
Replay postprocessing would presumably mean that that there's only one version in the database at any given time.

**Comment by Zarel** [comment]
Also, none of those protocol updates seem backwards-incompatible.

**Comment by Zarel** [comment]
And I still don't like them.

**Comment by Zarel** [comment]
I'm closing this. Of the issues you've named so far, I don't think any need to be backwards incompatible.

**Comment by Zarel** [comment]
If we ever need to make a backwards incompatible change, we'll probably need to fit the solution to the problem; this generic solution probably won't work for it anyway.

**Pull request closed without merging**
