### PR TITLE
Show team size in generations without team preview

### PR DESCRIPTION
**Pull request by QuiteQuiet**
Completes https://github.com/Zarel/Pokemon-Showdown/pull/3512

Also backwards compatible for servers where this isn't sent.

### CODE REVIEW

**Comment by Zarel** [comment]
I'm not sure if this is the best place to support this. It seems entirely different from how Team Preview is sent, which is four `|pokemon|` messages.

**Comment by Zarel** [comment]
In particular, arguments go in order from most to least important, and team size is too important to go after avatar.

**Comment by Zarel** [comment]
I might think a new `|teamsize|` message might be best, but I'm not sure. I'd like to hear others' opinions on this.

**Comment by QuiteQuiet** [comment]
>In particular, arguments go in order from most to least important, and team size is too important to go after avatar.

This sounds like a reasonable enough reason to change it to a message of it's own to be honest. Since I can't think of anywhere else it makes sense to send this information, and sending empty `|pokemon|playerid` messages to notify teamsize seems impractical at best.

**Comment by QuiteQuiet** [comment]
Would `|teamsize|playerid|size` work?

**Comment by Zarel** [comment]
Sounds good.

**Comment by QuiteQuiet** [comment]
Updated both

**Pull request merged**
