### PR TITLE
Tournaments: validate button should not submit a team when disabled

### PR DESCRIPTION
**Pull request by HoeenCoder**

### CODE REVIEW

**Comment by Zarel** [comment]
I swear we went over this. :|

**Comment by Zarel** [comment]
It's okay for a button that looks disabled to give an error message when you click on it.

**Comment by HoeenCoder** [comment]
If you mean doing nothing here, it returns 
```
Your team was rejected for the following reasons:

- You sent invalid team data. If you're not using a custom client, please report this as a bug.
```
so something needs to change, are you maybe suggesting an error reply popup from client? `You need to select a team first` maybe.

**Comment by Zarel** [comment]
Yeah.

**Comment by HoeenCoder** [comment]
This appears to have been forgotten and fixed elsewhere at some point so closing.

**Pull request closed without merging**
