### PR TITLE
Update move animations, round 8

### PR DESCRIPTION
**Pull request by Ridaz**
- Update Attract (and Infatuation status), Swagger, Covet, Play Rough, Return, Frustration, Thrash, Outrage
- Fixup Quiver Dance, Cosmic Power, Thunder, Close Combat, Meteor Mash. High Jump Kick
- Add new Angry & Heart particle (Credits to SailorCosmos)
- Update mudwisp particle (Credits to SailorCosmos)
- Anger Point ability now animates
- Captivate, Charm & Flatter, uses the Attract animation

Anger Point:
anger point

Attract:
attract

Close Combat:
close combat

Covet:
covet

Return & Play Rough:
return rough

Swagger:
swagger

Thunder:
thunder

### CODE REVIEW

**Comment by Zarel** [comment]
`graphics.js` is becoming kind of huge...

**Comment by Zarel** [comment]
This commit alone adds 1k lines... I wonder if you could express these animations in a more compact format...

**Comment by Ridaz** [comment]
Yeah. I was afraid of that. I'll see what I can do trying to update the animations from now on

**Comment by Zarel** [comment]
We can compile it to save some space, and I might look into making the API easier to use...

**Pull request merged**
