### PR TITLE
Track the previous item in the battle tooltip

### PR DESCRIPTION
**Pull request by urkerab**
I'm assuming this is what @Slayer95 wanted in PR #522.

I had to change the way itemEffect was set otherwise the display for Trick and Switcheroo was wrong.

### CODE REVIEW

**Comment by Zarel** [comment]
`.itemEffect` is still a horrible name. `previousItemEffect` maybe.

Also we might as well be consistent with server and use `prev` instead of `previous`.

**Comment by Slayer95** [comment]
I simply meant something like ``Draco Plate (Received with Trick)``, but I guess the more info the better.

**Comment by urkerab** [comment]
Item: Choice Scarf (tricked; was Leftovers)

Also includes the renames as requested.

**Comment by Zarel** [comment]
Do we really need to track `.itemEffect` as well...?

**Comment by Slayer95** [comment]
I'm not a fan of it, but I suppose it's relevant for Recycle...

**Comment by urkerab** [comment]
It's the best I could do within these constraints:
- If a Pokémon lost an item, then the item it lost should be shown (implemented by previous PR)
- The reason that it lost the item should also be shown (implemented by previous PR)
- `.item` should only contain an item that the Pokémon is actually holding (from comment on previous PR)
- The reason that it came into possession of the item should also be shown (from comment on previous PR)

**Comment by Zarel** [comment]
> The reason that it came into possession of the item should also be shown (from comment on previous PR)

Yeah, that was the part I was questioning. I don't really see a comment to that effect. Oh well, it's probably not a bad feature.

**Pull request merged**
