### PR TITLE
Add sorting options for Pokemon and moves in teambuilder

### PR DESCRIPTION
**Pull request by QuiteQuiet**
This can sort Pokemon by name or any of their stats. Moves can be sorted by name, base power, category, or type.

Examples: http://puu.sh/hhUjW.jpg http://puu.sh/hijMP.jpg

I tested some things, but I couldn't find if anything required <code>BattleChart.pokemon</code> to be in alphabetical order.

### CODE REVIEW

**Comment by TheImmortal** [comment]
Why is Meteor Mash first? Body Slam is also Physical and should be first alphabetically.

**Comment by QuiteQuiet** [comment]
Only because I forgot that would be a good idea. I'll get that sorted out.

**Comment by Zarel** [comment]
This conflicts with a pending optimization.

**Comment by QuiteQuiet** [comment]
This is most likely less important, so if you want to wait it's probably easy enough to merge this afterwards.

**Comment by Zarel** [comment]
Wow, the "pending optimization" wasn't actually pushed until December 2015... oh well, that's not too slow as far as PS development goes.

Teambuilder sorting is still planned, so I guess we can keep this pullreq open for that. I get the impression we should really make issues for pullreqs we want to implement but not in the way the pullreq does.

**Comment by Zarel** [comment]
Teambuilder sorting is done for Pokémon! Now to do it for moves...

**Comment by Zarel** [comment]
Pokémon sorting was implemented in 385c284c9691b15bb

Move sorting was implemented in 256885354e54def443a

**Pull request closed without merging**
