### PR TITLE
README: Add Travis Widget

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Zarel** [comment]
How much do people actually want this? If the build ever fails, it usually gets fixed within minutes, mostly because I get an email about it.

**Comment by Zarel** [comment]
I guess it looks good, but considering that the "build" is only a linter and some basic tests, it might be kind of deceptive to have it there, too...

**Comment by DeathlyPlays** [comment]
Yeah, it was really just a proposal

**Comment by Zarel** [comment]
...does anyone else have opinions?

**Comment by Slayer95** [comment]
Deceptive indeed.

**Comment by DeathlyPlays** [comment]
Deceptive...? How.... :/ Thought we just added things to make the server a better place.....

**Comment by Zarel** [comment]
Not your pull request, but the Travis icon itself would be deceptive.

**Comment by DeathlyPlays** [comment]
Ah gotcha....

**Pull request closed without merging**
