### PR TITLE
Don't track users in replays

### PR DESCRIPTION
**Pull request by urkerab**
As requested in PR #527 this moves the onus for enabling user tracking from the battle to the room.

### CODE REVIEW

**Comment by Zarel** [comment]
Maybe just set `this.room`?

**Comment by Zarel** [comment]
Better idea, set `this.roomid` in the battle.

I distrust the garbage collector. :P

**Comment by urkerab** [comment]
So you want something like `if (this.roomid) delete app.rooms[this.roomid].users[userid]?`

**Comment by Zarel** [comment]
Yes.

**Comment by urkerab** [comment]
Done.

**Pull request merged**
