### PR TITLE
Fix issues with horizontal scroll bar in Chrome

### PR DESCRIPTION
**Pull request by panpawn**
Several users have been complaining that a horizontal scroll bar is getting in the way in chat rooms and PM boxes, this fixes that.

### CODE REVIEW

**Comment by Zarel** [comment]
Can you make it not overflow horizontally?

**Comment by Zarel** [comment]
Specifically: `overflow-wrap: break-word;`

**Comment by panpawn** [comment]
That won't break vertical scrolling, right?

**Comment by Zarel** [comment]
No, it won't.

**Comment by Zarel** [comment]
image

**Comment by panpawn** [comment]
How is that?

**Comment by Zarel** [comment]
...you're supposed to have both.

**Comment by panpawn** [comment]
Updated

**Comment by panpawn** [comment]
... I have no idea how what this build is complaining about

**Comment by Zarel** [comment]
Heisenbugs make me uncomfortable... :/

**Pull request merged**
