### PR TITLE
Move Join other room up

### PR DESCRIPTION
**Pull request by acz13**
Discussion from dev room

### CODE REVIEW

**Comment by panpawn** [comment]
Screen cap?

**Comment by Zarel** [comment]
The phrasing "other" implies that it comes after the list of rooms. If you put it elsewhere, it probably needs a different name.

I also don't think "next to Hide" is a good place for it. Maybe I could see it above "Official chat rooms"?

**Comment by Zarel** [comment]
Maybe a straight-up "Join chatroom by name" box

**Comment by acz13** [comment]
@Zarel do you mean to the left of the Meloetta or where?

**Comment by panpawn** [comment]
He means above where it says "Official chat rooms" (big bold letters above the Lobby in that screen cap), and having it be a text box for the user to use, I believe

**Comment by Zarel** [comment]
Yes, what panpawn said.

**Comment by acz13** [comment]
Okay... I guess I'll do that when I get home

though honestly it's really quick someone else could probs do it

**Comment by Zarel** [comment]
...apparently no one did?

**Comment by acz13** [comment]
Lol,  
I'll start it now since it's the weekend

XD

**Comment by Zarel** [comment]
...?

**Pull request closed without merging**
