### PR TITLE
Stratagem dimensions added

### PR DESCRIPTION
**Pull request by Layell**
To be included with the next sprite/model update.

### CODE REVIEW

**Comment by Slayer95** [comment]
Status? @Zarel @Layell

**Comment by QxC4eva** [comment]
Dimensions are wrong. The front is 86x92 and the back 84x89

http://replay.pokemonshowdown.com/cap-138462505

The front view of Stratagem is noticeably blurry

**Comment by Layell** [comment]
Clearly I was lied to: http://i.imgur.com/brWom8a.png

I'll take care of this

**Comment by QxC4eva** [comment]
That's the dimensions of frame 1, which is correct.

**Pull request merged**
