### PR TITLE
Implement |unlink|roomhide| for room-specific message suppression

### PR DESCRIPTION
**Pull request by ascriptmaster**
For https://github.com/Zarel/Pokemon-Showdown/pull/2104

### CODE REVIEW

**Comment by Zarel** [comment]
hm

**Comment by ascriptmaster** [comment]
But what does "hm" mean, good sir

**Comment by Zarel** [comment]
I'm not sure this is ideal/necessary.

**Comment by ascriptmaster** [comment]
Why not? If we're going to allow messages to be hidden after a user is room banned, shouldn't it only hide messages from that room?

**Comment by Zarel** [comment]
If a user deserves to have their messages hidden, they're a spammer and they should be locked and have their messages hidden everywhere.

This is straight-up a trust problem and we really need to find a way to deal with it.

**Comment by Zarel** [comment]
But I don't have a better solution so I guess this is fine.

**Pull request merged**
