### PR TITLE
Fix active pokemon ability text in tooltip

### PR DESCRIPTION
**Pull request by luiscarloscb**
Currently the ability displayed in the active pokemon tooltip is the base ability of the pokemon, even after Skill Swap or similar skills.

For example, after Skill Swapping No Guard:
Before this change, it incorrectly displays No Guard as the current ability:
before 
After this change, it's more consistent with what the opponent sees:
after

### CODE REVIEW

**Comment by Zarel** [comment]
maybe it should be "Synchronize (base: No Guard)"

**Comment by luiscarloscb** [comment]
might as well, will do : )

**Comment by luiscarloscb** [comment]
Updated as recommended to show the current and base ability of the active pokemon, as a bonus it also works on the foe's active pokemon. 
capture

**Comment by luiscarloscb** [comment]
Accidentally deleted the branch, restored, then realized force pushing a quick fix actually prevents me from reopening this >-<, I think I'll just open a new one o-o

**Comment by Zarel** [comment]
in the future, reopen before pushing changes, and you'll be fine, I think

**Pull request closed without merging**
