### PR TITLE
Change PM windows in dark mode

### PR DESCRIPTION
**Pull request by Nixola**
In order to keep it consistent with the change in highlighted roomtab and highlighted message colour change, change the PM titlebar highlight colour to blue.

### CODE REVIEW

**Comment by Zarel** [comment]
do you have screenshots?

**Comment by Nixola** [comment]
Sure: [http://static.nixola.me/i/025977491.png](url)
The chat above (Bellematon) is hovered, the one below (HoeenHero) isn't

**Comment by Zarel** [comment]
That... isn't very visible...

Maybe make the non-notifying windows darker?

**Comment by Zarel** [comment]
(sorry, misclick)

**Comment by Nixola** [comment]
[Screen #1](http://static.nixola.me/i/380532763.png) from the top: highlighted and hovered, highlighted, inactive and hovered, inactive
[Screen #2](http://static.nixola.me/i/139363543.png) Active, not hovered
[Screen #3](http://static.nixola.me/i/290846168.png) Active, hovered

**Comment by Nixola** [comment]
@Zarel does this look better?

**Comment by Zarel** [comment]
tbh, no :/

**Comment by Zarel** [comment]
Closing, unmaintained and the final product still doesn't look like an improvement to me, and no one else has weighed in.

**Pull request closed without merging**
