### PR TITLE
Preact rewrite

### PR DESCRIPTION
**Pull request by Zarel**
HIGHLY UNFINISHED CODE

### CODE REVIEW

**Comment by Zarel** [comment]
This pull request **introduces 2 alerts** when merging d5532b921a68aad0f2d3573289a30eb20b3da8c2 into aa7ea99281890401bcc25e8ac04871b54ee895c6 - [view on LGTM.com](https://lgtm.com/projects/g/Zarel/Pokemon-Showdown-Client/rev/pr-6e94fe524d96dc6d397ddf33c9a66170a06777d8)

**new alerts:**

* 1 for Useless assignment to local variable
* 1 for Unused or undefined state property

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by walshyb** [comment]
Just curious, but do you plan on using redux (or something similar) to manage global state/data?

**Comment by Zarel** [comment]
Nope, we're using `PSModel` to manage global state, a class loosely inspired by the ECMAScript Observable proposal.

It's defined here:

https://github.com/Zarel/Pokemon-Showdown-Client/blob/77df694dee276373c54ba7f2c2d22a3a3861ddd0/src/client-core.ts#L67-L146

**Comment by Zarel** [comment]
In-progress shot!

image

**Comment by DaniellMesquita** [comment]
@Zarel 
Could you upload it to a subdomain, for easy live testing?

**Comment by Zarel** [comment]
I'll upload it when it gets closer to done.

As it is, it's very easy to test. Just check it out, run `node build`, and double-click `testclient-beta.html`.

**Comment by Zarel** [comment]
Superseded by #1229

**Pull request closed without merging**
