### PR TITLE
Change PS version 0.10.2 -> 0.10.3

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by Zarel** [comment]
Hm, we need to get that into `client.js` somehow, in a way that doesn't involve code duplication.

I guess we insert it as part of one of the build scripts.

**Comment by panpawn** [comment]
uh, which one

**Comment by Zarel** [comment]
`update` works

**Comment by Lord-Haji** [comment]
Z moves r worth a bump to 0.11.4
@panpawn

**Comment by Zarel** [comment]
@Lord-Haji, that's not how version numbers work. It'd be a bump to 0.11.0.

**Pull request closed without merging**
