### PR TITLE
Past Generation Alt Sprites

### PR DESCRIPTION
**Pull request by Layell**
Options: http://i.imgur.com/DVsNbcz.png

Allows users to choose different styled sprites.

### CODE REVIEW

**Comment by Zarel** [comment]
This is way too much and unnecessary...

**Comment by Zarel** [comment]
I guess I didn't think about this much at first until I realized it would be cluttering the Options menu

**Comment by Layell** [comment]
Would a popup be better and including that with some of the other sprite options?

**Comment by Slayer95** [comment]
Seconding @Layell 's proposal

**Comment by Zarel** [comment]
I'm not sure if that's the right place. Maybe a separate battle options menu?

**Comment by Layell** [comment]
I was about to say that as well, we'd just need to figure out a good button, perhaps a brush or eye?

**Comment by Layell** [comment]
Some FA icons:

http://fortawesome.github.io/Font-Awesome/icon/camera/
http://fortawesome.github.io/Font-Awesome/icon/eye/

Would require update to 4.4

http://fortawesome.github.io/Font-Awesome/icon/television/
http://fortawesome.github.io/Font-Awesome/icon/paint-brush/

**Comment by Zarel** [comment]
We should probably update FA anyway...

**Comment by Joimer** [comment]
I would love this update tbh, and I know a lot of peeps at LoA would as well.

**Comment by Layell** [comment]
Would having this as a button pop-up in options be preferable?

**Comment by Zarel** [comment]
so much code complexity for such a niche feature...

blah, a submenu could work... do _that_ many people find it important?

**Comment by Zarel** [comment]
Yes, @Layell, I'm fine having it as an Options submenu (a button pop-up).

**Comment by Zarel** [comment]
This was implemented as a command. UI may or may not come as part of the Preact rewrite.

**Pull request closed without merging**
