### PR TITLE
Darkmode CSS - fix format and background select button

### PR DESCRIPTION
**Pull request by WallyTheBully**
Darkmode CSS Update
These buttons should be updated for darkmode, I can provide more screenshots if needed

This pull request would update;
FormatSelect Button
AvatarlistSelect Button
BackgroundlistSelect Button

### CODE REVIEW

**Comment by Zarel** [comment]
Why?

**Comment by Zarel** [comment]
It's intentionally like the current look, I think it looks better that way, and also it's this way "selected" and "hovered" look different.

**Comment by WallyTheBully** [comment]
Basically the current background isn't the exact opposite of darkmode
The border shouldn't be in the same color
In whitemode background has a different color as a consequence the border should also be different in darkmode

**Comment by Zarel** [comment]
Dark mode doesn't need to be identical to a color-flipped light mode. I think it looks better like this.

**Comment by Zarel** [comment]
Closing. I still think the current implementation looks better than what you're changing it to. Especially since with my implementation, it's a lot easier to tell the difference between "selected" and "hovered".

**Pull request closed without merging**
