### PR TITLE
Allow spectators to switch sides

### PR DESCRIPTION
**Pull request by urkerab**
Apparently it's been suggested before, and it's definitely been suggested since, but the suggestion I found was http://www.smogon.com/forums/posts/5343275

Note that if you switch side while the battle is animating it will skip to the end; I couldn't work out how to skip to the current turn without restarting the background music.

### CODE REVIEW

**Comment by Joimer** [comment]
Additionally: Spectators seeing "your" side and "enemy" side is a little weird. Maybe it's about time we add player's name for spectators?

**Comment by DanUgore** [comment]
There's a thought

**Comment by Zarel** [comment]
I've been considering changing that phrasing, but "your" and "the opposing" kind of make it clear which one is which without having to look at the names of the players.

**Comment by Zarel** [comment]
As for switching sides: I think skipping to the current turn is worth restarting the background music.

**Comment by urkerab** [comment]
Well, I thought the only problem I had with skipping to the current turn was the background music, but but I'm struggling with the controls disappearing and I can't get them back.

**Comment by urkerab** [comment]
Whether the controls appeared depends on whether the turn has started or not. If it hasn't started then it happens to work because you get a turn end notification. The best I could do was to fake a turn end notification when the fast forward finished. (Obviously the original version always worked because it fast forwarded to the end of the turn rather than the beginning.)

Also the new FontAwesome has a better icon for Switch Sides, which is neat.

**Pull request merged**
