### PR TITLE
Updated tooltip for Truant activation

### PR DESCRIPTION
**Pull request by hvk3**

### CODE REVIEW

**Comment by Zarel** [comment]
The ability should be detected outside of the message. See how abilities are usually marked.

**Comment by hvk3** [comment]
Isn't this the only place where Truant is being handled?

**Comment by Zarel** [comment]
...

**Comment by hvk3** [comment]
Umm?

**Comment by Zarel** [comment]
It's easier just to show you if that explanation wasn't enough...

**Pull request closed without merging**
