### PR TITLE
Make disabled tour validator button not validate

### PR DESCRIPTION
**Pull request by TheMezStrikes**

### CODE REVIEW

**Comment by Zarel** [comment]
Why?

**Comment by TheMezStrikes** [comment]
Clicking the "validate" button in a random battle tournament validates the team, but the button class is set as disable so I figured it'd actually need to be disabled

**Comment by Zarel** [comment]
Wouldn't it make more sense to remove the validate button completely?

**Comment by TheMezStrikes** [comment]
My Javascript knowledge is very limited. So if you think that's the preferred course of action then I won't be of much help.

**Comment by Zarel** [comment]
TI's deathly afraid of client, so I guess this falls to me... :/

**Comment by Zarel** [comment]
It says "Your team is valid for this tournament".

I don't see a problem with this?

**Comment by TheMezStrikes** [comment]
My problem with this is that the button looks like it's disabled, is of the disabled class but is in fact fully functional. 
[21:29:05] Light HaZe: its just a little goofy imo

**Comment by Zarel** [comment]
"Does nothing except show a message telling you you didn't need to press it" does not mean "fully functional" to me, and is in fact the ideal reaction of a disabled button.

**Comment by Zarel** [comment]
Like, a good analogy is a locked door. A door that doesn't open when you try to open it is good, but even better is a door that tells you "this door is locked; use another door" when you try to open it.

**Comment by TheMezStrikes** [comment]
Wouldn't a message saying "Random Battle has random teams, so there is nothing to validate." be ideal then?

**Comment by TheMezStrikes** [comment]
The way I see the current situation, using your door analogy, is you walk up to a door with a huge lock on it that is clearly locked, but it still opens.

**Comment by Zarel** [comment]
Yes, that would certainly be more ideal, but the new situation is that random battle just doesn't display a validate button at all. Which is I think the best solution here.

**Pull request closed without merging**
