### PR TITLE
Add option to ignore in PM windows

### PR DESCRIPTION
**Pull request by sirDonovan**
Screenshot (updated): http://imgur.com/SQy6fML

### CODE REVIEW

**Comment by Slayer95** [comment]
Nice feature.
Though I think the UI would benefit the most from the button being next to the chatbox. The button could be `<i class="icon-exclamation-sign"></i>`

**Comment by sirDonovan** [comment]
I agree, it does look better that way. Updated screenshot: http://imgur.com/SQy6fML

**Comment by ascriptmaster** [comment]
It looks nice, but does it actually ignore?

**Comment by sirDonovan** [comment]
Yes, it works.

**Comment by ascriptmaster** [comment]
No, just making sure since the actual disabling code isn't in the diff.

**Comment by Slayer95** [comment]
(Missclicked <_<)

Assigning @Zarel because UI

**Comment by Zarel** [comment]
I was planning on doing it in a different way...

This way is sort of ugly, and the buttons are a bit too close to each other.

**Comment by Slayer95** [comment]
Ugly? D: Well, your call...
I noted the closeness issue as well, hence why I alternatively suggested a "next to chatbox" position.

We could add the ignore button in the user popup instead maybe?

**Comment by Zarel** [comment]
That might be better. I had a different idea though.

**Comment by sirDonovan** [comment]
Here's the button in the user popup, doesn't look as good as the PM window in my opinion: http://imgur.com/LdxbESq

What was your idea Zarel?

**Comment by Zarel** [comment]
I would rather have a "More" menu, anyway. Ignore shouldn't be given equal weight as Challenge and Chat.

**Comment by Irraquated** [comment]
I think it'd look nice inside a small settings icon top right of the user pop-up

**Comment by Joimer** [comment]
I like the first version, it's done like that in many UIs as well. It's fast and easy to use.

**Comment by sirDonovan** [comment]
Something happened while trying to update and fix merge conflicts, so I'll open a new pull request.

**Pull request closed without merging**
