### PR TITLE
Updates towards gen6 battle backgrounds.

### PR DESCRIPTION
**Pull request by The-Run**

### CODE REVIEW

**Comment by Zarel** [comment]
This should go in `sprites`, not a repository. Can you just give me a zip of the new backgrounds? And is there a way to get them all the same size as the old ones?

(You'll need to learn how to amend/squash at some point.)

**Comment by The-Run** [comment]
[Showdown Gen 6 Backgrounds.zip](https://github.com/Zarel/Pokemon-Showdown-Client/files/141651/Showdown.Gen.6.Backgrounds.zip)

**Comment by Layell** [comment]
I like these but would appreciate keeping the old backgrounds as well for gen 5 games.

**Comment by Zarel** [comment]
We'll be doing that.

**Comment by The-Run** [comment]
@Zarel I'll be sending some more bgs soon over the weekend so QuiteQuiet can lower the KB.

**Comment by The-Run** [comment]
@QuiteQuiet 
[gen6-ORAS BGs.zip](https://github.com/Zarel/Pokemon-Showdown-Client/files/149400/gen6-ORAS.BGs.zip)

**Comment by QuiteQuiet** [comment]
Here I guess: [oras-bgs.rar](https://www.dropbox.com/s/o5rji4kykkwjmec/oras-bgs.rar?dl=0)

I honestly don't think we need this many backgrounds, and we could cut out some of them without losing much.

**Comment by Zarel** [comment]
@QuiteQuiet, your rar only contains 6 backgrounds, of which 3 aren't really usable. Are there more in The Run's first zip that you omitted?

**Comment by QuiteQuiet** [comment]
@Zarel I only included the 6 new linked here, since I thought you gotten the other already. Since that apparently wasn't the right assumption: [bgs.rar](https://www.dropbox.com/s/j1qr1lc2gxhsjow/bgs.rar?dl=0)

**Comment by The-Run** [comment]
[allgen6 bgs.zip](https://github.com/Zarel/Pokemon-Showdown-Client/files/177693/allgen6.bgs.zip)

**Pull request closed without merging**
