### PR TITLE
Change /buttonkick to /buttonwarn

### PR DESCRIPTION
**Pull request by Irraquated**
(Also keeping /buttonkick as an alias) Makes the command much more understandable.

### CODE REVIEW

**Comment by QuiteQuiet** [comment]
Why is there a commit to remove tabs you yourself added, rather than not just add the tabs in the first place?

**Comment by Rhythms88** [comment]
@quiteQuiet they probably were automatically added from the program he used, and he just forgot to remove them

also he's probably squashing the commits

**Comment by Irraquated** [comment]
Yes I will be squashing the commits. @QuiteQuiet & @Rhythms88

**Comment by Irraquated** [comment]
Ok messed that up

**Comment by Irraquated** [comment]
Ok messed that up

**Pull request merged**
