### PR TITLE
Support capital letters in <<room>> links

### PR DESCRIPTION
**Pull request by sirDonovan**

### CODE REVIEW

**Comment by Zarel** [comment]
<<room>> links are roomids, capital letters are not allowed in roomids.

**Comment by sirDonovan** [comment]
I'm aware of that, but many users are not and try to use the feature with capital letters (even some staff have asked about it).

**Comment by Zarel** [comment]
The problem is that if they try to use room titles, they'll have lots of other problems because room titles are not unique, nor are room links deducible from room titles.

**Comment by Zarel** [comment]
Honestly, supporting titles in `/join` already annoys me. :|

**Pull request closed without merging**
