### PR TITLE
Change request protocol to fetch protocol

### PR DESCRIPTION
**Pull request by Frensly**
Fixes loading client improperly on new clients.

### CODE REVIEW

**Comment by Zarel** [comment]
http://php.net/manual/en/reserved.variables.php

I don't see `$_URI` on here...

**Comment by AustinXII** [comment]
Perhaps your confusing ``$_uri`` with ``$request_uri``?

**Comment by AustinXII** [comment]
Yeah I did mean that sorry my php is pretty rusty but also I was talking to Frensly :P

**Comment by Frensly** [comment]
Yes autstin your wrong actually, i was kind of, and $_SERVER['REQUEST_URI'] is a neat way i suppose. i mean i suggest using GET_URI instead of REQUEST_URI but im gonna test it first on myside

**Comment by Zarel** [comment]
You have literally never tested this considering you've sent three pullreqs so far and none of them work.

**Comment by Zarel** [comment]
I'm blocking you, Adam Snowden. :|

**Pull request closed without merging**
