### PR TITLE
Show tooltip for fainted pokemon

### PR DESCRIPTION
**Pull request by sirDonovan**
Moving the tooltip to a <code>span</code> allows it to be displayed for disabled buttons

### CODE REVIEW

**Comment by Zarel** [comment]
Alternatively, make "disabled" a class instead of actually disabling the button.

I think I'd rather do that.

**Comment by sirDonovan** [comment]
Yeah that's simpler, updated.

**Comment by Zarel** [comment]
Do you correctly handle what happens when someone clicks a button that looks disabled? :|

**Comment by sirDonovan** [comment]
Is something like this better? The messages are from ORAS.

**Pull request merged**
