### PR TITLE
Allow pm with no target to open a window

### PR DESCRIPTION
**Pull request by whalemer**

### CODE REVIEW

**Comment by MacChaeger** [comment]
I’d prefer this to require a comma but no message, as I think that users accidentally omitting the comma between the username and their message is more common (or at least more pressing) than users trying to open a PM window without actually sending a message.

**Comment by whalemer** [comment]
so no comma should error out as normal?

**Comment by Zarel** [comment]
Works for me. Why did you close this, though?

**Comment by whalemer** [comment]
I'm bad at git, apparently

**Pull request merged**
