### PR TITLE
 Fix Hidden Power IVs Spread during import for Gen7

### PR DESCRIPTION
**Pull request by Nephtyrix**
js/client-teambuilder.js
        Add this.curTeam in importTeam function
    js/storage.js
        Update importTeam function to get curTeam argument
        Update importTeam function to test gen for IVs spread

### CODE REVIEW

**Comment by Zarel** [comment]
This is an interesting idea, but it's probably the wrong way to do it.

**Comment by Zarel** [comment]
To clarify, I really appreciate the effort you put in here.

Unfortunately, passing moe and more parameters around just complicates the code. An ideal solution would be to have a concept of default and non-default IVs.

**Comment by Nephtyrix** [comment]
Ok, I clearly understand, the only one problem who attempt on this is the grouped import function between import a single pokemon on TeamBuilder and import all team from backup, the last one get the Gen (===[Gen7ou]===) so this issue don't occur, but not on a single pokemon. 
I told that cause the concept of default and non-default IVs is based on Gen. 
I know, we can't add more parameters. I need to find an other solution for that !

**Comment by Nephtyrix** [comment]
Ok, I clearly understand, the only one problem who attempt on this is the grouped import function between import a single pokemon on TeamBuilder and import all team from backup, the last one get the Gen (===[Gen7ou]===) so this issue don't occur, but not on a single pokemon. 
I told that cause the concept of default and non-default IVs is based on Gen. 
I know, we can't add more parameters. I need to find an other solution for that !

**Pull request closed without merging**
