### PR TITLE
Implement team sorting in teambuilder

### PR DESCRIPTION
**Pull request by Joimer**
Looks like this http://i.imgur.com/iMKEmSe.png
Can't believe it was this easy.

### CODE REVIEW

**Comment by Zarel** [comment]
Looks sort of ugly. :/

**Comment by Zarel** [comment]
It's also sort of unclear what the arrows mean, which is probably a bigger problem (rest of that page looks ugly anyway).

**Comment by Joimer** [comment]
Well, the whole page is ugly, heh. I think the arrows are pretty straightforward, you have them in both directions unless it's the topmost one or bottommost one, or no arrows if only one team.

Any suggestions?

**Comment by Zarel** [comment]
The thing is that arrows mean way too much. The way the in-team move buttons work is with a Move button with a Move icon, which I think is clearer.

**Comment by Joimer** [comment]
But 1 click > 2 clicks imo. The move buttons and menu would look worse if you have, say, more than 20 teams, don't you think so?

**Comment by Zarel** [comment]
How so? We might be thinking of different things if you think it'd look worse.

**Comment by Zarel** [comment]
Well, we now have drag-and-drop sorting, which is better, so I assume this can be closed.

**Pull request closed without merging**
