### PR TITLE
Support XY/ORAS icons and gender: Revisited.

### PR DESCRIPTION
**Pull request by Golui**
I have updated Slayer95's solution (found [here](https://github.com/Zarel/Pokemon-Showdown-Client/pull/275/files)) to the newest version of the client, while also making edits that make it look nicer.

### CODE REVIEW

**Comment by Zarel** [comment]
Can you provide screenshots? Can you also keep commit summaries to 50 characters wide?

**Comment by Golui** [comment]
Here are screenshots:

http://imgur.com/IXGlg4n,tCPIZNY,6r8J1BC,SojVxg1

**Comment by Golui** [comment]
Cleaned up commit messages.

**Comment by Zarel** [comment]
Team tabs: Look fine, but those have never been an issue.

Team dropdown in main menu: Did you widen the main menu? Will this cause problems on phones? also the icons look too far apart. The horizontal padding on the other menu groups also look weird, especially with the lack of horizontal padding on the main team selector. The wider gaps also look ugly, make sure there are no margins between the icons; you can use negative margins if necessary.

Teams on the teambuilder team list: Here you have more space to work with, but the wider gaps still look ugly, as above.

`!dt`: Looks weird, but this one's not your fault.

The teambuilder pokemon selector: How does it look? I don't see a screenshot.

Mini-teams under the trainersprite in the battle UI: This is the most important one. How does it look? I don't see a screenshot.

**Comment by Layell** [comment]
@Golui here is an updated sheet with CAP 20, here is hoping that pic can get up too now : )

https://www.dropbox.com/s/0qlzx37tlsibdw3/master.png?dl=0

**Comment by Layell** [comment]
For feedback:

mon selector: http://i.imgur.com/yutmpAv.png

in battle: http://i.imgur.com/jnuWR5Y.png

**Comment by Zarel** [comment]
This design won't be accepted; further discussion in #590

**Pull request closed without merging**
