### PR TITLE
Add -ability messages for Anticipate and Forewarn

### PR DESCRIPTION
**Pull request by ascriptmaster**
Also allow Forewarn to read the Pokemon giving the move in Gen5+.

### CODE REVIEW

**Comment by TheImmortal** [comment]
You didn't remove the anticipation from -activate.

**Comment by TheImmortal** [comment]
Also Forewarn.

**Comment by ascriptmaster** [comment]
Reverse compatibility for replays :\

**Comment by Zarel** [comment]
If it gives any information other than the fact that the Pokémon has the ability, it goes in `-activate`, not `-ability`.......

**Comment by ascriptmaster** [comment]
All right then. I'll update the protocol doc accordingly later (and probably push it myself instead of opening a PR)

**Comment by ascriptmaster** [comment]
progress?

**Pull request merged**
