### PR TITLE
Fix PP counting for Trick Room/Pressure interaction

### PR DESCRIPTION
**Pull request by xfix**
Not using `Array#some`, as I believe this part of the code has to work in old web browsers.

### CODE REVIEW

**Comment by xfix** [comment]
This is different to #1223 by the way, it's just a coincidence there were two Pressure-related changes recently.

**Comment by Zarel** [comment]
You can just polyfill `Array#some`, btw.

**Comment by Zarel** [comment]
Also isn't Pressure +1 per Pressure user, not just +1 overall?

**Comment by xfix** [comment]
Oh right.

**Pull request merged**
