### PR TITLE
Auto-hide format menu into sections

### PR DESCRIPTION
**Pull request by panpawn**

### CODE REVIEW

**Comment by panpawn** [comment]
Screen caps:

**Comment by panpawn** [comment]
Can someone help me out with the tests?

**Comment by TheImmortal** [comment]
That doesn't look nice at all.

**Comment by Zarel** [comment]
This is also not at all what I was suggesting in the thread...

**Comment by panpawn** [comment]
>This is also not at all what I was suggesting in the thread...

The formats could be moved server-side to for it to look like what you were suggesting in the thread.

**Comment by panpawn** [comment]
>That doesn't look nice at all.

What about it looks particularly bad? Is it the actual organization of the formats, or the way it's still split into columns, or...?

**Comment by Zarel** [comment]
I'm not sure what you're saying? What does moving it server-side accomplish?

**Comment by panpawn** [comment]
>What does moving it server-side accomplish?

Format reogranization

**Comment by panpawn** [comment]
Although, this does lack single-format support currently.  I'll add that soon, but in the meantime, what else is different about this than what you guys had in mind?

**Comment by Zarel** [comment]
Oh. Yes. You'll need server-side changes for this to take effect.

**Comment by AustinXII** [comment]
I agree with TI, this is ugly, the options should no be going vertical

**Comment by panpawn** [comment]
... as opposed to horizontal? They definitely would look better vertical than they would horizontal. Anyways, I think keeping support for different columns is a good idea, so I don't plan on removing that.

**Comment by Zarel** [comment]
I personally think it's too many columns and several other things, but I proposed a pretty decent design imo. :<

**Comment by AustinXII** [comment]
@panpawn it overlapping into the rooms section is ugly though

**Comment by panpawn** [comment]
>I personally think it's too many columns and several other things, but I proposed a pretty decent design imo. :<

I mean, I plan on keeping it all as 1 format with the design you had proposed Zarel, but I would very much like to keep support for multiple columns.

>@panpawn it overlapping into the rooms section is ugly though

... It currently does that already. When I'm done, it won't on main. >_>...

**Comment by TheImmortal** [comment]
This doesn't really reduce clutter; it's practically the same size as the list now. All it does is make it more difficult to select what you want to play. And these buttons are not appealing at all. My idea or Zarel's idea, or like practically any idea posted in the thread is good.

**Pull request closed without merging**
