### PR TITLE
Bring string utility functions to parity with server counterparts

### PR DESCRIPTION
**Pull request by Slayer95**
- toName is updated to deal with zalgo and LTR text.
- toId is now infinite-recursion-safe, and equivalent to toUserid.
- Tools.escapeHTML and Tools.sanitizeHTML no longer crash for some input.
- Tools.getString is made available as getString

(We actually need more inter-branch PRs)

### CODE REVIEW

**Comment by Zarel** [comment]
The rest is good, but I'm not sure `getString` is necessary?

**Comment by Zarel** [comment]
The worst those can do is crash iirc, and we trust servers at least not to send data of the wrong type over...

**Comment by Slayer95** [comment]
``getString`` is at least needed internally by other functions to prevent crashes (I assert that the server shouldn't be able to crash the client by sending bad (TM) data. Making it private would require some closures that I'd actually find harder to justify.

I suspect, nevertheless that we actually do need to use toString to avoid crashes, in the context of jQuery#text calls.

**Comment by Zarel** [comment]
Fair.

**Pull request merged**
