### PR TITLE
Show power of generic Z moves in tooltips

### PR DESCRIPTION
**Pull request by urkerab**
- Not sure how I should clone the move to change its name/category/type
- Not implemented showing Z effect of status moves yet
- Not implemented unusual Z moves such as Z-Weather Ball

### CODE REVIEW

**Comment by Zarel** [comment]
This is a good idea, but ideally we probably want it sent server-side...

**Comment by urkerab** [comment]
I've looked into sending the data server-side and although it's certainly feasible for the request to include the base power and category I can't actually see how to extract that from the tooltip code.

**Comment by Zarel** [comment]
The tooltip code needs to be seriously rewritten, anyway :|

**Comment by urkerab** [comment]
The other benefit of this client-side change is that it will become possible to show the full effect of a status Z-move, which the client isn't really set up to do otherwise, unless you're planning to do that as part of your tooltip rewrite?

**Comment by Zarel** [comment]
You're right that this is an improvement over the current situation......... but I still think tooltips need to be rewritten; they're a mess right now.

**Pull request merged**
