### PR TITLE
Add protocols for RoomGames in battle rooms

### PR DESCRIPTION
**Pull request by panpawn**
WIP.

### CODE REVIEW

**Comment by Slayer95** [comment]
XSS alert ಠ_ಠ

**Comment by panpawn** [comment]
``Tools.sanitizeHTML`` fixes that right

**Comment by Zarel** [comment]
We should probably actually parse args differently depending on the first thingy.

**Comment by panpawn** [comment]
?

**Comment by Zarel** [comment]
I'll show you what I mean in the code

**Comment by Zarel** [comment]
See 76690a5001f8b2a7092

**Comment by panpawn** [comment]
... so, should I just use ``args[1]`` here instead of ``args.slice(1).join('|')``?

Wouldn't that make it so that if a game contains ``|`` in it's HTML, that it would just stop there?

**Comment by Zarel** [comment]
...see https://github.com/Zarel/Pokemon-Showdown-Client/commit/76690a5001f8b2a7092938af7899c672f5a3c6d1#diff-b502a7533835db1d325f945bc2b7fc08R6588

**Comment by panpawn** [comment]
After thinking about this more, this kind of seems more like a hack than anything else.

Then again, doing it how I don't think it'd be a hack would be repeating a lot of code that's used for battles, so I'm really not sure what to do.

Is this approach to this a good idea, or should it probably be a separate thing similar to battle rooms?

**Comment by Zarel** [comment]
Yes, it's a hack, but do you have a better idea?

**Comment by Zarel** [comment]
@panpawn are you just going to let this stagnate? This is important!

**Comment by panpawn** [comment]
This was incomplete - iirc, it didn't handle clearing the weather background

**Comment by panpawn** [comment]
Yeah, there's also the ``Join Battle`` button that has to be taken care of, too.

There should probably be a ``|initializegame|`` protocol or something that the server sends that initially clears all of this stuff.

**Pull request closed without merging**
