### PR TITLE
Tooltips: Don't call a BP penalty a boost

### PR DESCRIPTION
**Pull request by MacChaeger**

### CODE REVIEW

**Comment by asgdf** [comment]
https://github.com/Zarel/Pokemon-Showdown-Client/pull/925
Yours is more concise, but on the other hand "(Rivalry weakened)" sounds a bit weird to my ears so idk. Zarel's call I suppose.

**Comment by Zarel** [comment]
"boosted by ABILITY" and "weakened by ABILITY" would be the more grammatically correct way to do this, but I rather dislike wordiness.

Maybe "&times;FACTOR ABILITY"?

**Comment by asgdf** [comment]
"×0.75 Rivalry"? Feels a bit too minimalistic to me, maybe "×0.75 due to Rivalry"?

**Comment by Zarel** [comment]
"×0.75 from Rivalry"

**Comment by Zarel** [comment]
Closing because #925 is a better basis.

**Pull request closed without merging**
