### PR TITLE
Support XY/ORAS icons and displaying gender/item on Team Preview

### PR DESCRIPTION
**Pull request by Slayer95**
Previews:
http://imgur.com/cpSe3RP,MVfkbbW,Vj17ZmV,DUt9ASN

Files for sprites/
sprites/xyicons-pokeball-sheet.png http://i.imgur.com/DTykNE0.png
sprites/xyicons-sheet.png http://i.imgur.com/uaiWiUJ.png

Protocol: |poke|[PLAYER]|[DETAILS]|item

### CODE REVIEW

**Comment by ascriptmaster** [comment]
It's been a while since this has been touched. I would suggest this: have gender and whether there's an item in the mouse-over text, like HP and status. Then, during the actual team preview at the beginning, have the icons maybe appear next to the sprites at the center screen?

**Comment by Layell** [comment]
I've been getting a few comments here and there about the ORAS icons, can we get those up at least while we figure out the other stuff.

**Comment by Zarel** [comment]
>It's been a while since this has been touched. I would suggest this: have gender and whether there's an item in the mouse-over text, like HP and status. Then, during the actual team preview at the beginning, have the icons maybe appear next to the sprites at the center screen?

That's exactly what I recommend (well, my idea is fancier, but that one works).

>I've been getting a few comments here and there about the ORAS icons, can we get those up at least while we figure out the other stuff.

How do you propose fitting them?

**Comment by Layell** [comment]
I would ideally like to see no overlap in the icons, because we simply don't know how future icons will border on the regular size limits (see kyurem formes bw2).

However I see the logic in not reworking the layout, so I am fine with no layout changes as well. This appears to be the easiest option so I'd say go for it.

**Comment by Joimer** [comment]
I just want to note that showing whether a Pokémon has an item or not is competitively important. One could discuss gender, but that's minor.

**Comment by Zarel** [comment]
Yes, Joim, we all know. :|

Layell, I sort of want to resize the trainer bars, but right now the layout is sort of precisely calculated to be 4:3 (480x360) without trainerbars and 16:9 (640x360) with trainerbars.

**Comment by Zarel** [comment]
Also, have you tested how they look in teambuilder?

Also note that this will probably break PSdex, which uses these icons, too.

**Comment by Zarel** [comment]
Oh, you have looked in teambuilder, and it looks weird. :|

**Comment by Zarel** [comment]
Point is, this is a pretty big change to the design. :/

**Comment by Zarel** [comment]
Seriously, though, every single one of those screenshots looks uglier than what we currently have.

**Comment by ascriptmaster** [comment]
ok now what

**Comment by Zarel** [comment]
This design won't be accepted; further discussion in #590

**Pull request closed without merging**
