### PR TITLE
Fix modjoin problem

### PR DESCRIPTION
**Pull request by ascriptmaster**
Solution as described in https://github.com/Zarel/Pokemon-Showdown/issues/1787

I don't know if this actually works because this exact problem isn't exactly the easiest thing to test given the `testclient.html` stuff we have.

### CODE REVIEW

**Comment by ascriptmaster** [comment]
@Zarel, do you think this is a good solution?

**Comment by ascriptmaster** [comment]
errrrrgh. bump @Zarel again

**Comment by Zarel** [comment]
Not a horrible solution

**Comment by ascriptmaster** [comment]
Beautiful. Is there any way to even test this? I've found it virtually impossible to check with `testclient.html`

**Comment by Slayer95** [comment]
It works. Tested at http local custom client.
But I don't think there is a need to break support for `'|deinit|namerequired`. It could be useful for roomkick-like commands, or to hook it to /modjoin.

**Comment by ascriptmaster** [comment]
Did I accidentally break `namerequired`? Whoops.

**Comment by ascriptmaster** [comment]
Hmmm, I don't understand. Did I really break `namerequired` with this code?

**Comment by Slayer95** [comment]
What we currently use is `|noinit|namerequired|`. You broke support for `|deinit|namerequired|`, which is potentially useful; that's what I mean.

**Comment by ascriptmaster** [comment]
So when I get the chance I should change it to `if (data === 'namerequired' || (!isdeinit && !this.user.named))`? All right.

**Comment by ascriptmaster** [comment]
something like this, except idk again because idk how to set it up to test

**Comment by ascriptmaster** [comment]
poke poke

**Comment by Zarel** [comment]
This actually is a pretty good fix.

**Comment by Zarel** [comment]
I ended up fixing it server-side, though.

**Comment by ascriptmaster** [comment]
Since Zarel is evidently fixing the whole thing serverside, we don't need this.

**Pull request closed without merging**
