### PR TITLE
Change (PU) to Untiered

### PR DESCRIPTION
**Pull request by KrisXV**
This would be so much easier if we could just allow ZU teambuilder support directly via ZUBL and ZU

### CODE REVIEW

**Comment by bumbadadabum** [comment]
Why are we changing the name of a tier to something that gets cut off in the teambuilder? It looks really bad

**Comment by KrisXV** [comment]
I was asked to make it Untiered, I’m fine with any name. I was just doing what I was asked to do

**Comment by bumbadadabum** [comment]
In that case I'm asking the person who asked you why he chose this name.

**Comment by KrisXV** [comment]
@theimmortal

**Comment by TheImmortal** [comment]
This what Smogon uses to define Pokemon that do not make it into the lowest usage-based tier. (OU) (PU) and such should be reserved for Megas imo since those are accurate. But classifying Untiered Pokemon as "PU by technicality" is wrong and doesn't match Smogon.

One solution could be abbreviating it to "U", much like AG or any other tier.

**Comment by bumbadadabum** [comment]
Yeah UT or something or "no tier"

**Comment by KrisXV** [comment]
If everyone is fine with UT, I'll update it in a little bit

**Comment by Zarel** [comment]
I don't like "UT". "U" is a bit more acceptable, except that could be confused with Ubers. "None"?

**Comment by TheImmortal** [comment]
Or you could make it display a dash. That seems nicer.

**Comment by Zarel** [comment]
I'm fine with the dash.

**Pull request merged**
