### PR TITLE
A C Script

### PR DESCRIPTION
**Pull request by Taskforce-Zero**

### CODE REVIEW

**Comment by Taskforce-Zero** [comment]
ok

**Comment by TheImmortal** [comment]
ok

**Comment by xfix** [comment]
You should print new line at end of program, otherwise the prompt will appear just after the printed text. Also, you should include `<stdio.h>` in order to use I/O functions.

Please read the style guide that is yet to written because submitting a pull request again.

**Comment by Zarel** [comment]
@TheImmortal, @xfix, Can we not do all these semi-joke responses?

@Taskforce-Zero, seriously, what are you trying to do here? This is the repository for the client for the Pokémon Showdown battle simulator, it's not the place to submit random C code.

**Comment by xfix** [comment]
I sorta would like to have a style guide however for a client so it could be pointed to, oh well.

**Pull request closed without merging**
