### PR TITLE
Redundant checks in teambuilder

### PR DESCRIPTION
**Pull request by hvk3**

### CODE REVIEW

**Comment by Zarel** [comment]
Damn it, TI, this is wrong. :|

**Comment by Zarel** [comment]
```
			if (stats.spa > stats.atk && moveCount['Special'] > 1) offenseBias = 'Special';
			else if (stats.atk > stats.spa && moveCount['Physical'] > 1) offenseBias = 'Physical';
			else if (moveCount['Special'] > moveCount['Physical']) offenseBias = 'Special';
```

was supposed to be this :|

**Comment by TheImmortal** [comment]
Both lines looks exactly the same to me...?

**Comment by Zarel** [comment]
Yes, but obviously they weren't intended to be the same.

**Comment by Zarel** [comment]
Now I'm going to get merge conflicts when I push the change that fixes it correctly...

**Comment by hvk3** [comment]
Should I make the changes?

**Comment by hvk3** [comment]
#Zarel?

**Comment by Zarel** [comment]
Feel free.

**Pull request merged**
