### PR TITLE
Various Graphics Animation Changes

### PR DESCRIPTION
**Pull request by Pikachuun**
Basically, I tried to make them more accurate to the games, except for Spark + Nuzzle, which I believe have too "strong" animations at this time.
The list:

Mist Ball [Old animation moved to Moonblast]; Luster Purge; Hyperspace Hole; Spark + Nuzzle; Icy Wind + Powder Snow; Blue Flare [Update; fire is now blue]; Dragon Ascent [Update; collision effects are greener].

### CODE REVIEW

**Comment by Zarel** [comment]
@ascriptmaster what do you think of these?

**Comment by ascriptmaster** [comment]
I remember someone mentioning that it was a bad idea to have a graphic that's dedicated to a single move only. Although, Gen 4 and up have blue/purple flames for Sacred Fire (especially in gen 6, which is entirely blue), so you could use the blue flame for that move as well.

**Comment by Layell** [comment]
We could do blue flame for Wil-O-Wisp too, ingame ORAS it's purplish but description is: "The user shoots a sinister, bluish-white flame at the target to inflict a burn."

**Comment by ascriptmaster** [comment]
The flame for Will-o-Wisp is purple in Gen 6 from what I know. But we could use blue.

**Comment by Zarel** [comment]
Blue is close enough, yes.

**Comment by ascriptmaster** [comment]
fireball - copy

I thinkered around with the hue/saturation/brightness on the fireball image and got this, I wonder if it'll look better haha

**Comment by Zarel** [comment]
Our original fireball image sucks; can you find a freely-licensed fireball that doesn't suck?

**Comment by ascriptmaster** [comment]
Alas I'm not good at finding freely-licensed fireballs or flames. Maybe I should just Photoshop something, but then I can't guarantee that it's any better than what we have.

**Comment by Zarel** [comment]
Worth a try.

**Comment by ascriptmaster** [comment]
fire

If you say it's worth a try, then here is my try.

**Comment by Zarel** [comment]
On first glance it looks better than what we had before, but it might be nice to see screenshots side-by-side.

Also, multiple fireball sprites might make some animations look better.

**Comment by Slayer95** [comment]
@ascriptmaster @Pikachuun  what's the state of this?

**Comment by ascriptmaster** [comment]
Oh, I forgot to finish crafting a better flame image.

@Pikachuun, can you shelve Blue Flare change for now? I'll work on it later and we can merge the rest for now.

**Pull request closed without merging**
