### PR TITLE
Fix grassy terrain battle text

### PR DESCRIPTION
**Pull request by Alumn2000**
https://www.smogon.com/forums/threads/fix-grassy-terrain-battle-text.3652044/

testclient html#battle-gen7ou-989733005

### CODE REVIEW

**Comment by Alumn2000** [comment]
Problem: It works for Grassy terrain but I don't know if I broke something (even if I checked locally) + we have "The opposing [Pokemon]'s HP was restored." and not "The opposing [Pokemon] had its HP restored." because I don't know how to implement that, but I think that's ok.

**Comment by Zarel** [comment]
@DaWoblefet is this message only used for Grassy Terrain? If so, it should be associated with Grassy Terrain, not the generic `healFromEffect`.

**Comment by Zarel** [comment]
And yes, you did break something.

**Comment by Zarel** [comment]
You see this:

```js
	grassyterrain: {
		start: "  Grass grew to cover the battlefield!",
		end: "  The grass disappeared from the battlefield.",
	},
```

Your message should have been added there:

```js
	grassyterrain: {
		start: "  Grass grew to cover the battlefield!",
		end: "  The grass disappeared from the battlefield.",
		heal: "  [POKEMON]'s HP was restored.",
	},
```

**Comment by Alumn2000** [comment]
evidence1 horn leech + wish messages works (so drain punch, ... will work too)
evidence2 soft-boiled message works (so recover, roost, ... will work too)
evidence3 Wiki berry messages works (so Sitrus berry, Aguav berry, berry juice, ... will work too)

It was all under Grassy terrain (mb). Will try to see tomorrow if it works if grassy terrain isn't there but I was checking the local and normal client, and everything seemed ok.

**Comment by Alumn2000** [comment]
Ah, I didn't saw your comment Zarel. Ok, will do it tomorrow.

**Comment by DaWoblefet** [comment]
I would have to review all the healing effects to make sure, but offhand I think this is Grassy Terrain only.

**Comment by Zarel** [comment]
Thanks!

**Pull request merged**
