### PR TITLE
Add suppress interstice option

### PR DESCRIPTION
**Pull request by Teremiare**

### CODE REVIEW

**Comment by CrestfallPS** [comment]
Not Zarel, but when I brought up doing this last year it was rejected by multiple tech upper staff. Let's hope things have changed!

**Comment by Zarel** [comment]
I would call this 'skip interstice' and not 'hide interstice'.

Actually, I wouldn't use "interstice" at all. Something more like "Don't warn for untrusted links".

@CrestfallPS who rejected it and why?

**Comment by Teremiare** [comment]
So something like that?

**Comment by panpawn** [comment]
As long as this isn't enabled by default, I see no issue with it?  The prompt is very clear so users will generally know what it means before clicking it and finding out later.

**Pull request merged**
