### PR TITLE
Fix issue with HP colours

### PR DESCRIPTION
**Pull request by Irraquated**

### CODE REVIEW

**Comment by Zarel** [comment]
?

This doesn't seem right...

**Comment by Irraquated** [comment]
How so @Zarel ?

**Comment by Zarel** [comment]
It seems that until now, the guarantee was that a Pokémon in red HP would have both the `hp-yellow` and `hp-red` classes.

This changes it so that it only has one of them, which may have unpredictable consequences.

**Comment by Zarel** [comment]
It also doesn't do it very cleanly, so it has the same problems the previous implementation had.

**Comment by Irraquated** [comment]
Fair call, @Zarel what if instad of changing what is currently changed in the pull to instead have: On line 2933 add `$hp.addClass('hp-yellow');` ?

**Comment by Zarel** [comment]
It depends. Most likely it's getting out of sync at some other place.

**Comment by Zarel** [comment]
We could replace all the `$hp.addClass('hp-red');` with `$hp.addClass('hp-yellow hp-red');`

**Comment by Irraquated** [comment]
That was the other way I was thinking of going bout it @Zarel, should I also do this with `else $prevhp.addClass('prevhp-red');` and replace with `else $prevhp.addClass('prevhp-yellow prevhp-red');` ?

**Comment by Zarel** [comment]
Yes, probably.

**Comment by Irraquated** [comment]
There's one more thing I have to do before this can be committed, will have to do it later as i'm on mobile.

**Comment by Slayer95** [comment]
Superceeded by https://github.com/Zarel/Pokemon-Showdown-Client/pull/444

**Comment by Zarel** [comment]
Apparently the correct spelling is 'supersede'. 'Supercede' is an alternate spelling, but it's less common (at least in US English).

**Pull request closed without merging**
