### PR TITLE
Support 'choice' battle messages

### PR DESCRIPTION
**Pull request by Slayer95**
Intended for parsing player battle choices and possibly doing something with that information in the future -doing nothing for now.

### CODE REVIEW

**Comment by Zarel** [comment]
Can you clarify?

**Comment by Slayer95** [comment]
With the ref-ed server-side PR, when battle decisions are commited, players' decisions will be stored in the replay split log, and sent back to them as confirmation.

- Storage in replay, as I mentioned in the server PR, will be useful to deal with bug reports. (But I clicked move X! No, you cancelled. Yes, and were encored, etc.)
- Confirmation, as it was discussed in Smogon PM, is potentially useful to keep a better track of own Pokémon, specially in the context of Illusion, lack of Nickname Clause, etc.

**Comment by ascriptmaster** [comment]
Wait, is the server continuously sending `choice` during a battle? Wouldn't that be a leak?

Or does it send in replays only

**Comment by Slayer95** [comment]
It uses the ``split`` feature, @ascriptmaster. So no leaks.

**Pull request merged**
