### PR TITLE
handle unfound pokemon in -curestatus

### LINKED ISSUE #1062: Zoroark/HealBell
My understanding of heal bell: the server sends a -curestatus message to the client for each pokemon the client knows about. Zoroark, as always, throws a wrench into things -- the server thinks the client has seen a Zoroark, whereas the client has either

1) not seen a zoroark or
2) seen an illusion.

I haven't read the server code, but given that this doesn't crash all the time with healbell, I can only imagine 2) is the reason.

I've attached a replay log that should fail: [zoroark-heal-bell.txt](https://github.com/Zarel/Pokemon-Showdown-Client/files/1541822/zoroark-heal-bell.txt)

I'm not sure if the fix here should be client or server-side because I'm not familiar with how this is handled in the cartridge games.

### PR DESCRIPTION
**Pull request by yuzeh**
Should fix #1062.

Let me know how I should be testing this... I tested locally and everything seems to work well.

### CODE REVIEW

**Comment by Zarel** [comment]
Are you aware of the failed test?

**Comment by yuzeh** [comment]
@Zarel yes! I think... you mean `npm test`?

I just fixed that issue.

**Comment by yuzeh** [comment]
@Zarel anything else you want me to do for this issue?

**Comment by Zarel** [comment]
I'm not sure I _like_ this implementation, but I can't think of obvious changes.

**Pull request merged**
