### PR TITLE
Zweilous/Swanna model update

### PR DESCRIPTION
**Pull request by QuiteQuiet**

### CODE REVIEW

**Comment by Zarel** [comment]
Err, why isn't Layell pullreqqing this?

**Comment by Zarel** [comment]
Who are you? o_O

**Comment by QuiteQuiet** [comment]
I'm pullreqqing it because instead of me telling Layell the dimensions and then he changes them, he told me to just change them myself (http://puu.sh/f8ukr).

Also I was the guy who fixed the models so the sizes needed changing in the first place.

**Comment by Zarel** [comment]
Works for me.

**Pull request merged**
