### PR TITLE
Prompt the user to forfeit before leaving a game room

### PR DESCRIPTION
**Pull request by HoeenCoder**
Creates a forfiet popup if a user tries to leave a room where there is an ongoing room game, and they are a player in the game.

### CODE REVIEW

**Comment by Zarel** [comment]
Looks good!

**Comment by AustinXII** [comment]
Pls don’t forget allowing all staff to /blockpms

**Comment by Zarel** [comment]
I thought that already happened?

**Comment by AustinXII** [comment]
@Zarel Nope. hoeen said he was waiting to finish some client update for help tickets and he’d just bunch it together when I asked him if I could just do it before since it was taking a while (which is completely understandable)

**Comment by AustinXII** [comment]
You’re probably thinking of when Hoeen allowed leaders to block pms to which I suggested all staff having that luxury, which you agreed on.

**Comment by HoeenCoder** [comment]
oh right! thanks for the reminder @AustinXII ill add that to my help tickets PR as that needs to be merged to allow this to function properly in tickets.

**Pull request merged**
