### PR TITLE
Highlight the current user in elimination tournaments

### PR DESCRIPTION
**Pull request by urkerab**
The original idea was to draw a dashed border for the team but as it turns out you get it on the battles you win too.

### CODE REVIEW

**Comment by sirDonovan** [comment]
Do you have a screenshot of this?

**Comment by urkerab** [comment]
This is a mockup I created using developer tools (I did join a tournament to test this but didn't think to take a screenshot at the time).
capture

**Comment by kotarou3** [comment]
hm, it doesn't stand out very much. Maybe tint it with a bit of yellow?

**Comment by Zarel** [comment]
blah, those colors aren't very good. How are the colors chosen, anyway? What do green and red mean?

**Comment by kotarou3** [comment]
Green means the bolded person won, while red means lost

**Comment by urkerab** [comment]
We can tweak the colours of course... for this simulated screenshot I adjusted the colours so that they would all have the same apparent luminance (Y).
tournament

**Comment by Zarel** [comment]
I generally avoid having green and red as the only hues, because of Christmas implications. I usually do red and gray, or red and blue, or gray and green, or something like that.

**Comment by Zarel** [comment]
Also, if the color coding is who won, how is who's bolded determined?

**Comment by ascriptmaster** [comment]
Bolded seems to be who won that round. Red/Green seems to be whether the winner of that round won the next round. At least, that's what seems to be the case.

**Comment by Zarel** [comment]
ooooooooh

**Comment by Zarel** [comment]
Maybe we should get rid of the color coding? The colors are kinda ugly and it's not like it's clear anyway.

**Comment by kotarou3** [comment]
I'm a terrible designer - do what you want

**Comment by urkerab** [comment]
I asked around and people seem to like the colours.

For this version I also made the player's name italic. (This also affects round robin, because I wanted to be consistent.) With this change, I would be happy to revert the colours back to the original, since now it doesn't matter so much that the borders aren't so visible.

**Comment by Zarel** [comment]
I don't like the tour design in general but it's not really a problem with this change specifically.

Your color change is good and should be kept.

**Comment by urkerab** [comment]
So, which options would you like me to keep, the colour change, the border change and/or the text decoration change?

**Comment by Zarel** [comment]
Use the colors from your simulated screenshot. For everything else, just use your own judgment.

**Comment by urkerab** [comment]
OK, so the current diff has the colour changes and the dotted border, but not the italic font.

**Pull request merged**
